import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import CommonLayout from "@/components/commonLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
            <body>
                <CommonLayout>
                    {children}
                </CommonLayout>
            </body>
        </html>
    );
};

export default RootLayout;
