name: Deploy to meta2day_front

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: Akiaka-T1/next
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"

      - name: Push to destination repository
        run: |
          git remote add target https://${{ secrets.MYREPOSITORYKEY }}@github.com/JONGHYUNVAN/meta2day_front.git
          git push target master:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.MYREPOSITORYKEY }}

      - name: Capture error log
        if: failure()
        run: |
          echo "Deployment failed. Capturing logs..."
          echo "Commit Message: ${{ github.event.commits[0].message }}" > error_log.txt
          dmesg >> error_log.txt
          echo "##[error]$(cat error_log.txt)"
          echo "::set-output name=error-log::$(cat error_log.txt)"

      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: error_log.txt
