- name: Push to personal repository
  if: github.ref == 'refs/heads/master'
  run: |
    echo "Setting up git user config"
    git config --global user.email "whdgus808@naver.com"
    git config --global user.name "JONGHYUNVAN"
    
    echo "Adding files to git"
    git add .
    
    echo "Committing changes"
    git commit -m "Automated commit message" || echo "No changes to commit"

    echo "Pushing to personal repository"
    git push https://$GH_PAT@github.com/JONGHYUNVAN/meta2day_front.git HEAD:main || echo "Push failed"
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
