on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: Akiaka-T1/next
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name "JONGHYUNVAN"
          git config --global user.email "whdgus808@naver.com"

      - name: Push to destination repository
        run: |
          git remote add target https://<GITHUB_TOKEN>@github.com/JONGHYUNVAN/meta2day_front.git
          git push target master:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.MYREPOSITORYKEY }}
        with:
          commit-message: ${{ github.event.commits[0].message }}
